// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFU1d5qxHojBuisBpbUBQfc-FEqAjtPe8',
    appId: '1:755316157048:web:8295dfc6c4ca79bd335b8d',
    messagingSenderId: '755316157048',
    projectId: 'flutter-login-app-86aab',
    authDomain: 'flutter-login-app-86aab.firebaseapp.com',
    storageBucket: 'flutter-login-app-86aab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_wm5OEhuBW9qCXzldcDHX7nWRECXFDE',
    appId: '1:755316157048:android:844b875457d0d486335b8d',
    messagingSenderId: '755316157048',
    projectId: 'flutter-login-app-86aab',
    storageBucket: 'flutter-login-app-86aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUhVLZOBqwFCp6AzHq8yNiC913S_PVSQ',
    appId: '1:755316157048:ios:64231ef3d83defc3335b8d',
    messagingSenderId: '755316157048',
    projectId: 'flutter-login-app-86aab',
    storageBucket: 'flutter-login-app-86aab.appspot.com',
    iosClientId: '755316157048-cqf6duq33qfhakhvv3vvhd4mdrhe34cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );
}
